#!/bin/bash

# Create the file
touch '\*\\'"Best School"\''\\*$\?\*\*\*\*\*:)'

# Add the text "Best School" to the file
echo "Best School" > '\*\\'"Best School"\''\\*$\?\*\*\*\*\*:)'

# Add a new line to the end of the file
echo >> '\*\\'"Best School"\''\\*$\?\*\*\*\*\*:)'
